on:
  workflow_dispatch:
    inputs:
      version:
        type: string
  # push:
  release:
    types: [released]

env:
  VERSION: ${{ inputs.version || (github.event_name == 'release' && github.ref_name || '') }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: viamrobotics/build-action@v1
      with:
        version: ${{ env.VERSION }}
        ref: ${{ github.sha }}
        key-id: ${{ secrets.viam_key_id }}
        key-value: ${{ secrets.viam_key_value }}
